version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo "Empaquetando el proyecto..."
      # Usamos package.yml como nombre de salida para que coincida con tu Pipeline
      - aws cloudformation package --template-file template.yml --s3-bucket implementacion-artifacts-yennyferg --output-template-file package.yml

artifacts:
  files:
    - package.yml
    - index.js
    - package.json
