version: 0.2

phases:
  install:
    commands:
      - yarn install
  build:
    commands:
      - echo "Saltando build porque los archivos ya están listos..."
  post_build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket implementacion-artifacts-yennyferg --output-template package.yml

artifacts:
  files:
    - package.yml
  discard-paths: yes
