version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo Build started on `date`
      - # Aquí puedes agregar comandos si necesitas instalar dependencias ligeras
      - export BUCKET=implementacion-artifacts-yennyferg
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml

artifacts:
  files:
    - outputtemplate.yml
    - index.js
    - package.json
