AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs20.x
    Timeout: 300
    MemorySize: 1024

Mappings:
  RegionMap:
    us-east-1:
      RegionShortName: ''
    us-west-1:
      RegionShortName: 'uw1'

Resources:
  ContactDynamoDB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: yenny-contact-v3
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      Tags:
        - Key: "SYSTEM"
          Value: work-shop

  ContactApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: yenny-contact-api
      EndpointConfiguration: REGIONAL
      StageName: prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent,id-token'"
        AllowMethods: "'DELETE,GET,OPTIONS,POST,PUT'"
        AllowOrigin: "'*'"

  ContactCreateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: yenny-contact-create
      CodeUri: ./
      Role: !GetAtt ContactCreateRole.Arn
      Environment:
        Variables:
          TABLE_NAME_CONTACTS: !Ref ContactDynamoDB
      Events:
        CreateRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /
            Method: POST

  ContactCreateRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'YennyContactCreateRole-${AWS::Region}-v3'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['dynamodb:GetItem', 'dynamodb:PutItem']
                Resource: !GetAtt ContactDynamoDB.Arn

  ContactDeleteLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: yenny-contact-delete
      CodeUri: ./
      Role: !GetAtt ContactDeleteRole.Arn
      Environment:
        Variables:
          TABLE_NAME_CONTACTS: !Ref ContactDynamoDB
      Events:
        DeleteRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /{email}
            Method: DELETE

  ContactDeleteRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'YennyContactDeleteRole-${AWS::Region}-v3'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['dynamodb:GetItem', 'dynamodb:DeleteItem']
                Resource: !GetAtt ContactDynamoDB.Arn

  ContactGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: yenny-contact-get
      CodeUri: ./
      Role: !GetAtt ContactGetRole.Arn
      Environment:
        Variables:
          TABLE_NAME_CONTACTS: !Ref ContactDynamoDB
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /{email}
            Method: GET

  ContactGetRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'YennyContactGetRole-${AWS::Region}-v3'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['dynamodb:GetItem']
                Resource: !GetAtt ContactDynamoDB.Arn

  ContactUpdateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: yenny-contact-update
      CodeUri: ./
      Role: !GetAtt ContactUpdateRole.Arn
      Environment:
        Variables:
          TABLE_NAME_CONTACTS: !Ref ContactDynamoDB
      Events:
        PutRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /{email}
            Method: PUT

  ContactUpdateRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'YennyContactUpdateRole-${AWS::Region}-v3'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['dynamodb:GetItem', 'dynamodb:UpdateItem']
                Resource: !GetAtt ContactDynamoDB.Arn

